sudo: false
language: python
python: 2.7
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=flake8
install:
  - pip install tox
  - pip install pytest pytest-cov coveralls
script:
  - tox
after_success:
  - py.test --cov outlier_utils tests
  - coveralls
